-   repo: local
    hooks:
    -   id: lint
        name: govuk linter
        entry: bundle exec govuk-lint-ruby app lib
        language: system
    -   id: bundle-check
        name: bundle-check
        entry: bundle check || bundle install
        language: system
    -   id: rake
        name: rake testing
        entry: bundle exec rake
        language: system
