inherit_gem:
  rubocop-govuk: 
    - config/default.yml

Style/ConditionalAssignment:
  Enabled: false
Style/StringLiterals:
  Enabled: false

AllCops:
  Include: 
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
  Exclude:
    - 'bin/**'