default: &default
    aws_region: <%= ENV["AWS_REGION"] %>
    cognito_aws_access_key_id: <%= ENV["COGNITO_AWS_ACCESS_KEY_ID"] %>
    cognito_aws_secret_access_key: <%= ENV["COGNITO_AWS_SECRET_ACCESS_KEY"] %>
    cognito_client_id: <%= ENV["AWS_COGNITO_CLIENT_ID"] %>

# Make the rest of your groups inherit from default
development:
    <<: *default

test:
    <<: *default

production:
    <<: *default
    s3_aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
    s3_aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
    aws_bucket: <%= ENV["AWS_BUCKET"] %>
